[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/pricetracker-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/auth/login"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
